---
title: "appliedg"
output: html_document
date: '2022-10-23'
---

Question 1
```{r }
require(raster)
# import the data files
dem61 = raster("data/dem_gries_1961.asc")
dem07 = raster("data/dem_gries_2007.asc")
mask61 = raster("data/glacier_mask_gries_1961.asc")
mask07 = raster("data/glacier_mask_gries_2007.asc")

dem61mat = matrix(0, 201, 237)
dem61mat[,] = dem61[,]
dem07mat = matrix(0, 201, 237)
dem07mat[,] = dem07[,]
mask61mat = matrix(0, 201, 237)
mask61mat[,] = mask61[,]
mask07mat = matrix(0, 201, 237)
mask07mat[,] = mask07[,]

# calculate the volume change
delta_h = matrix(0, 201, 237)
sigma_h = 0

for (i in 1: 201){
  for (j in 1:237){
    if (mask07mat[i, j] == 1 | mask61mat[i, j] == 1){
      delta_h[i, j] = dem07mat[i, j] - dem61mat[i, j]
      sigma_h = sigma_h + as.numeric(delta_h[i, j])
    }
  }
}


mean_area = (sum(mask07mat == 1) + sum(mask61mat == 1)) * 625 / 2 # m^2
volume_change = sigma_h * 625 # m^3

# transform into mass change
mass_change_rate = 850 * volume_change / (2007 - 1961) 
# mass_change_rate = -3252121929 kg/a 
specific_mcr = mass_change_rate / mean_area
# specific_mcr = -559.2343
```

Question 2
```{r}
# select Andermatt station for its year coverage and completeness in precipitation and temperature data
# https://www.meteoswiss.admin.ch/product/output/climate-data/homogenous-monthly-data-processing/data/homog_mo_ANT.txt
meteoseries = read.table("data/homog_mo_ANT.txt", skip = 28)
colnames(meteoseries) = c("Year", "Month", "Temperature", "Precipitation")

```

Question 3
```{r}
z_ref = 1435
t_melt = 0
t_solid = 2
# select data of 1961-2007
meteoseries_6107 = meteoseries[meteoseries$Year < 2009 & meteoseries$Year > 1960,]
meteoseries_6107 = meteoseries_6107[10:573, ]

grid_n = 0
accumulation_6107 = 0
Tempmat = matrix(0, 201, 237)
for (m in 1:nrow(meteoseries_6107)){
  grid_n = 0
 for (i in 1:201){
   for (j in 1:237){
     if (mask07mat[i, j] != 0){
       # T = Tref - (z-zref) * dT/dz 
       Tempmat[i,j] = (meteoseries_6107[m, 3] - (dem07mat[i,j] - z_ref) * 0.0065)
       # count how many grids on the glacier fit r_s = 1
       if (Tempmat[i,j] < t_solid){grid_n = grid_n +1}
     }
   }
 }
  # C = Pref * rs = Pref * (number of grids allowing r_s = 1)
  accumulation_6107 = accumulation_6107 + 625 * grid_n * meteoseries_6107[m, 4] / 1000
}

# C = accumulation_6107 = 325124201
# C means the cumulative accumulation from 1961 - 2007
```

```{r}
# calculate the accumulated temperature on grids separately 
accutemp6107 = 0
Tempmat = matrix(0, 201, 237)
for (m in 1:nrow(meteoseries_6107)){
 for (i in 1:201){
   for (j in 1:237){
     if (mask07mat[i, j] != 0){
       # T = Tref - (z-zref) * dT/dz 
       Tempmat[i, j] = (meteoseries_6107[m, 3] - (dem07mat[i,j] - z_ref) * 0.0065)
       # for grid fits T > T0 = 0, calculate its accutemp of the month
       if (Tempmat[i, j] > t_melt){accutemp6107 = accutemp6107 + 625 * 30.42 * Tempmat[i,j]}}
   }
 }
}
# accutemp6107 = 44152674067
 # DDF = (C-B)/T
DDF = (accumulation_6107 - (mass_change_rate * 46 / 1000)) / accutemp6107 
# 1000 for density 1000kg/m^3
# unit of DDF: m degree^-1 day^-1
```


Question 4
```{r}
meteoseries_1021 = meteoseries[meteoseries$Year < 2023 & meteoseries$Year > 1909,]
meteoseries_1021 = meteoseries_1021[10: 1353, ]
z_ref = 1435
t_melt = 0
t_solid = 2

# C
grid_n = 0
accumulation_1021 = 0
Tempmat = matrix(0, 201, 237)
yearly_accu = matrix(0, 112, 2)
yearly_accu[, 1] = c(1910:2021)
y = 1
c = 1
for (m in 1:nrow(meteoseries_1021)){
  grid_n = 0
 for (i in 1:201){
   for (j in 1:237){
     if (mask07mat[i, j] != 0){
       Tempmat[i,j] = (meteoseries_1021[m, 3] - (dem07mat[i,j] - z_ref) * 0.0065)
       if (Tempmat[i,j] < t_solid){grid_n = grid_n +1}
     }
   }
 }
  if (c < 13){
    yearly_accu[y, 2] = yearly_accu[y, 2] + 625 * grid_n * meteoseries_1021[m, 4] / 1000
    c = c + 1
  }
  else {
    c = 2
    y = y + 1
    yearly_accu[y, 2] = 625 * grid_n * meteoseries_1021[m, 4] / 1000
  }
  accumulation_1021 = accumulation_1021 + 625 * grid_n * meteoseries_1021[m, 4] / 1000
}

# accumulation_1021 = 749755159 m^3 (volume of water on the whole glacier from precipitation)

# A
accutemp1021 = 0
Tempmat = matrix(0, 201, 237)
yearly_abla = matrix(0, 113, 2)
yearly_abla[, 1] = c(0, 1910:2021)
y = 2
c = 1
for (m in 1:nrow(meteoseries_1021)){
 for (i in 1:201){
   for (j in 1:237){
     if (mask07mat[i, j] != 0){
       Tempmat[i, j] = (meteoseries_1021[m, 3] - (dem07mat[i,j] - z_ref) * 0.0065)
       if (Tempmat[i, j] > t_melt){accutemp1021 = accutemp1021 + 625 * 30.42 * Tempmat[i,j]}}
   }
 }
  if (c < 12){
    c = c + 1
  }
  else {
    yearly_abla[y, 2] = accutemp1021 - sum(yearly_abla[1:(y - 1), 2])
    y = y + 1
    c = 1
  }
}

yearly_abla[, 2] = yearly_abla[, 2] * DDF

ablation1021 = accutemp1021 * DDF
# accutemp1021 = 107255504055
# ablation1021 = 1153192373 # m^3

# cumulative B
cumulative_mass1021 = accumulation_1021 - ablation1021
avg_mass1021 = cumulative_mass1021 / (2021-1910)
print(cumulative_mass1021)
print(avg_mass1021)

testb = matrix(0, 112, 2)
testb[, 1]= yearly_accu[,1]
testb[, 2] = yearly_accu[,2]-yearly_abla[2:113,2]
par(mar=c(2,4,1,1))
par(mfrow=c(3,1))
plot(yearly_accu, xlab = "year", ylab = "yearly accumulation", pch = 20, col = "royalblue4")
plot(yearly_abla[2:113,], xlab = "year", ylab = "yearly ablation", pch = 20, col = "indianred")
plot(testb, xlab = "year", ylab = "yearly mass balance", pch = 20, col = "springgreen4")
```
Question5
```{r}
# [5.1]
# V = c*A^{gamma}
# c = 0.03, gamma = 1.36
volume_2007 = 0.03 * ( sum(mask07mat == 1) * 0.000625 ) ^ 1.36
# volume_2007 = 0.2657891 km^3

# [5.2]

# when lost 50% volume, mass also lost 50%.
mass_2007 = volume_2007 * 10 ^ 9 * 900 #kg
wevolume_50per = 0.5 * mass_2007 / 1000 #m^3
# mass_2007 = 239210211315 kg
# wevolume_50per = 119605106 m^3

wevolume_mat = matrix(0, 16, 2)
wevolume_mat[1, 2] = mass_2007/1000
wevolume_mat[, 1] = c(2007:2022)
year_50per_within21 = matrix(0, 16, 1)
for (i in 98: 112){
 wevolume_mat[i-96, 2] =  wevolume_mat[i-97, 2] + testb[i, 2]
 if (wevolume_mat[i-96, 2] < wevolume_50per){
   year_50per_within21[i-96, 1] = wevolume_mat[i-96, 1]
   }
}
for (i in 1:16){
  if (year_50per_within21[i,1] == 0) {year_50per_within21[i,1] = NA}
}
print(year_50per_within21[which.min(year_50per_within21[, 1]),1])
# wevolume_2021 is the w.e of the lost glacier mass in 2021 
# wevolume_2021 = 47862997 m^3
# in the upper for-loop, we check the glacier mass from 2007-2021, if the mass already goes down below the 50% volume, we return the year, if not, we will go through the below code for further prediction.

#=========further prediction===========================
# avg_rate = mean(testb[82:112, 2])
# future_we = matrix(0, 200, 2)
# future_we[, 1] = c(2021:2220)
# future_we[1, 2] = wevolume_mat[15, 2]
# year = 2
# while (future_we[year-1, 2] > wevolume_50per){
#   future_we[year, 2] = future_we[year-1, 2] + avg_rate
#   year = year + 1
# }
# 
# year_50per = future_we[which.min(future_we[, 2])-1, 1]
#=========further prediction===========================


# the result might be over-estimated, i.e. the time might be even sooner, since the trend of mass balance rate indicated more ablation in time evolution, and thus more volume loss.

```

